"""Add Feedback model

Revision ID: db5e7942eac1
Revises: 588d609e1d55
Create Date: 2025-04-22 21:13:29.487830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db5e7942eac1'
down_revision = '588d609e1d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index('unique_user_product_rating')

    op.drop_table('rating')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('average_rating')
        batch_op.drop_column('total_ratings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ratings', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('average_rating', mysql.FLOAT(), nullable=True))

    op.create_table('rating',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='rating_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='rating_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index('unique_user_product_rating', ['user_id', 'product_id'], unique=True)

    # ### end Alembic commands ###
